defaults:
  - env/maniskill_put_on_plate_in_scene_25_main@env.train
  - env/maniskill_put_on_plate_in_scene_25_main@env.eval
  - model/pi0_5@actor.model
  - hybrid_engines/fsdp@actor.fsdp_config
  - weight_syncer/patch_syncer@weight_syncer
  - experiment/maniskill_pi05_flow_sde_base@_global_
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

runner:
  logger:
    experiment_name: "maniskill_ppo_openpi_pi05_flow_sde"
